local CharacterData = {
	Chara = {
		Id = "Chara",
		DisplayName = "Chara",
		Role = "Rushdown knife fighter",
		Description = "Fast, aggressive pressure with sharp confirms and dangerous close-range punishment.",
		Cost = 0,
		Free = true,
		Prototype = false,
		ReleaseCharacter = true,
		Public = true,
		Moves = {
			"Knife Dash",
			"Slash Barrage",
			"Red Slash",
			"Killing Intent",
			"Special Hell",
		},
	},

	Sans = {
		Id = "Sans",
		DisplayName = "Sans",
		Role = "Trickster zoner",
		Description = "Projectile pressure, traps, blue magic control, and punishing ultimate confirms.",
		Cost = 0,
		Free = true,
		Prototype = false,
		ReleaseCharacter = true,
		Public = true,
		Moves = {
			"Bone Shot",
			"Bone Zone",
			"Blue Snare",
			"Gaster Blaster",
			"Bad Time",
		},
	},

	Toriel = {
		Id = "Toriel",
		DisplayName = "Toriel",
		Role = "Protective fire bruiser",
		Description = "A disciplined royal guardian who controls space with fire and punishes careless pressure.",
		Cost = 1,
		Currency = "Dust",
		Free = false,
		Locked = true,
		Prototype = true,
		ReleaseCharacter = false,
		Public = false,
		DeveloperOnly = true,
		WIP = true,
		Lore = "She enters the Hollow Route because it imitates a child in danger.",
		Moves = {
			"Mother's Grip",
			"Flame Pillar",
			"Guardian Break",
			"Royal Snap",
			"Royal Pyre",
		},
	},

	DisbeliefPapyrus = {
		Id = "DisbeliefPapyrus",
		DisplayName = "Disbelief Papyrus",
		Cost = 35,
		Free = false,
		ReleaseCharacter = false,
		Public = false,
		DeveloperOnly = true,
		WIP = true,
	},

	GlitchtaleFrisk = {
		Id = "GlitchtaleFrisk",
		DisplayName = "Glitchtale Frisk",
		Cost = 40,
		Free = false,
		ReleaseCharacter = false,
		Public = false,
		DeveloperOnly = true,
		WIP = true,
	},
}

return CharacterData
