return {
	DefaultDance = {
		DisplayName = "Default Dance",
		Description = "The reliable first move on every battle stage.",
		AnimationName = "DefaultDance",
		Cost = 0,
		Starter = true,
		Free = true,
		Order = 1,
		Looped = true,
		CanMove = false,
		CancelOnMove = true,
		CancelOnJump = true,
		CancelOnDamage = true,
		MusicName = "DefaultDanceMusic",
	},

	TPose = {
		DisplayName = "T-Pose",
		Description = "Stand perfectly still and let the pressure do the talking.",
		AnimationName = "TPose",
		Cost = 25,
		Order = 2,
		Looped = true,
		CanMove = false,
		CancelOnMove = true,
		CancelOnJump = true,
		CancelOnDamage = true,
	},

	Headless = {
		DisplayName = "Headless",
		Description = "A spooky pose for players who like a dramatic entrance.",
		AnimationName = "Headless",
		Cost = 25,
		Order = 3,
		Looped = true,
		CanMove = false,
		CancelOnMove = true,
		CancelOnJump = true,
		CancelOnDamage = true,
		--VisualMode = "Headless",
	},

	Spin = {
		DisplayName = "Spin",
		Description = "Keep moving while showing off a clean rotating step.",
		AnimationName = "Spin",
		Cost = 50,
		Order = 4,
		Looped = true,
		CanMove = true,
		CancelOnMove = false,
		CancelOnJump = true,
		CancelOnDamage = true,
		SoundName = "SpinSound",
	},

	LoudLaugh = {
		DisplayName = "Loud Laugh",
		Description = "A short laugh with maximum confidence.",
		AnimationName = "LoudLaugh",
		Cost = 50,
		Order = 5,
		Looped = false,
		CanMove = false,
		CancelOnMove = true,
		CancelOnJump = true,
		CancelOnDamage = true,
		Duration = 3,
		SoundName = "LoudLaughSound",
	},

	CleanGroove = {
		DisplayName = "Clean Groove",
		Description = "A stylish looping groove with its own beat.",
		AnimationName = "CleanGroove",
		Cost = 100,
		Order = 6,
		Looped = true,
		CanMove = false,
		CancelOnMove = true,
		CancelOnJump = true,
		CancelOnDamage = true,
		MusicName = "CleanGrooveMusic",
	},
}
